### ISSUE TITLE
Por corregir

### ISSUE THREAD

**Issue by gabo592** [gabo592/Mer#1]
# Corregir

- [x] Componer el diseño del frame para actualizar perfil

# TO-DO

- [x] Frame para eliminar la cuenta o perfil
- [x] Frame para el punto de venta o caja

**Comment by gabo592** [comment]
Frame de la caja ya hecho pero sin terminar

**Comment by gabo592** [comment]
Todas las correcciones hechas
